


```{r}
# Required libraries
library (tidyverse)
library(camcorder)

```





```{r}
episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-08/episodes.csv')
sauces <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-08/sauces.csv')
seasons <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-08/seasons.csv')

view(episodes)
view(sauces)
view(seasons)
```

```{r}
# Start recording
gg_record(
  dir = 'temp.', # where to save the recording
  device = "jpeg", # device to use to save images
  width = 19,      # width of saved image
  height = 14,     # height of saved image
  units = "in",   # units for width and height
  dpi = 300       # dpi to use when saving image
)

```




```{r}

#Adding fonts for plots and axis 
my_theme <- function() {
  theme_classic() +                        
    theme(
      plot.title = element_text(hjust=0.5, vjust = 1, size = 40, color = "#FFCE00", family = "PT Sans Pro Narrow"),
      plot.subtitle = element_markdown(hjust=0.5, vjust = 1, size = 28, family = "PT Sans Pro Narrow", color = "white"),
      plot.background = element_rect(fill = "black"),
      axis.text.x = element_text(vjust=0.1, hjust = 0.1 , size=15, color = "white"),
      axis.text.y = element_blank(),
      axis.title.x = element_text(family = "Roboto", size=18, color = "white"),
      axis.title.y = element_blank(),
      panel.background = element_rect(fill= "black" , color = "black"),
      plot.caption = element_text(hjust = 0.5, family = "Roboto", size=24, color = "white")
    )
}



# Join data 
data <- left_join(episodes, seasons, by = "season")

# Calculate counts
data <- data %>%
  group_by(season) %>%
  summarise(finished = sum(finished), 
            tapped_out = n() - sum(finished))  

# Calculate totals
data <- data %>% 
  mutate(total = finished + tapped_out)
  
# Calculate percentages
data <- data %>%
  mutate(finished_pct = finished/total * 100) 


# Round percentages  
data <- data %>%
  mutate(labels = percent(finished_pct, accuracy = 0.01))



subtitle_text <- paste0(
"Hot Ones is a popular YouTube show where celebrities answer questions while eating increasingly spicy wings. ",
"<br> The fill colors represent two categories: <b style= 'color:#FFCE00' > Finished </b> and <b style= 'color:#E4342E' > Tapped Out </b> </br> <br> ")

caption_text <- "\n Source: Wikipedia via #TidyTueday, Name: Saurabh Jadhav"



# Plot stacked bar chart
ggplot(data, aes(x=season, y=finished, fill="Finished")) +
  geom_bar(stat='identity', width = 0.9, position=position_dodge(0.7)) + 
  geom_bar(aes(y = tapped_out, fill = "Tapped Out"), stat='identity', width = 0.9,position=position_dodge(0.5)) +
  geom_text(aes(label = paste0(round(finished_pct, 2),'%')), vjust = -0.5, size= 5.75 , color = "white") +
  scale_fill_manual(values=c("#FFCE00","#E4342E")) + my_theme()+
  labs( title = "\nGUEST PERFORMANCE TRENDS ON HOT ONES BY SEASON \n",
        subtitle = subtitle_text, caption = caption_text , x = "Season" )  + guides(fill = 'none') 


gg_stop_recording()



gg_playback(
name = "hotones.gif",
  first_image_duration = 4,
  last_image_duration = 20,
  frame_duration = 0.3
)


```

